version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: moviebooking
    volumes:
      - mongo_data:/data/db
    networks:
      - moviebox-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/moviebooking
    networks:
      - moviebox-network

  movie-service:
    build: ./movie-service
    container_name: movie-service
    ports:
      - "5002:5002"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/moviebooking
    networks:
      - moviebox-network

  theater-service:
    build: ./theater-service
    container_name: theater-service
    ports:
      - "5003:5003"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/moviebooking
    networks:
      - moviebox-network

  booking-service:
    build: ./booking-service
    container_name: booking-service
    ports:
      - "5004:5004"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/moviebooking
    networks:
      - moviebox-network

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "5005:5005"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/moviebooking
    networks:
      - moviebox-network

volumes:
  mongo_data:

networks:
  moviebox-network:
    driver: bridge