apiVersion: apps/v1
kind: Deployment
metadata:
  name: theater-service
  namespace: moviebox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: theater-service
  template:
    metadata:
      labels:
        app: theater-service
    spec:
      containers:
      - name: theater-service
        image: kastrov/theater-service:latest
        ports:
        - containerPort: 5003
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/moviebooking"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
